# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ross/vehicle_status.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class vehicle_status(genpy.Message):
  _md5sum = "aaafa5c64ffa127d3610f378ae59fa7f"
  _type = "ross/vehicle_status"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/String Battery_Status
std_msgs/String Velocity_Status
std_msgs/String Alt_Status 
std_msgs/String Position_x
std_msgs/String Position_y

================================================================================
MSG: std_msgs/String
string data
"""
  __slots__ = ['Battery_Status','Velocity_Status','Alt_Status','Position_x','Position_y']
  _slot_types = ['std_msgs/String','std_msgs/String','std_msgs/String','std_msgs/String','std_msgs/String']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Battery_Status,Velocity_Status,Alt_Status,Position_x,Position_y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(vehicle_status, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.Battery_Status is None:
        self.Battery_Status = std_msgs.msg.String()
      if self.Velocity_Status is None:
        self.Velocity_Status = std_msgs.msg.String()
      if self.Alt_Status is None:
        self.Alt_Status = std_msgs.msg.String()
      if self.Position_x is None:
        self.Position_x = std_msgs.msg.String()
      if self.Position_y is None:
        self.Position_y = std_msgs.msg.String()
    else:
      self.Battery_Status = std_msgs.msg.String()
      self.Velocity_Status = std_msgs.msg.String()
      self.Alt_Status = std_msgs.msg.String()
      self.Position_x = std_msgs.msg.String()
      self.Position_y = std_msgs.msg.String()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.Battery_Status.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Velocity_Status.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Alt_Status.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Position_x.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Position_y.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.Battery_Status is None:
        self.Battery_Status = std_msgs.msg.String()
      if self.Velocity_Status is None:
        self.Velocity_Status = std_msgs.msg.String()
      if self.Alt_Status is None:
        self.Alt_Status = std_msgs.msg.String()
      if self.Position_x is None:
        self.Position_x = std_msgs.msg.String()
      if self.Position_y is None:
        self.Position_y = std_msgs.msg.String()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Battery_Status.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Battery_Status.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Velocity_Status.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Velocity_Status.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Alt_Status.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Alt_Status.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Position_x.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Position_x.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Position_y.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Position_y.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.Battery_Status.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Velocity_Status.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Alt_Status.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Position_x.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Position_y.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.Battery_Status is None:
        self.Battery_Status = std_msgs.msg.String()
      if self.Velocity_Status is None:
        self.Velocity_Status = std_msgs.msg.String()
      if self.Alt_Status is None:
        self.Alt_Status = std_msgs.msg.String()
      if self.Position_x is None:
        self.Position_x = std_msgs.msg.String()
      if self.Position_y is None:
        self.Position_y = std_msgs.msg.String()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Battery_Status.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Battery_Status.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Velocity_Status.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Velocity_Status.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Alt_Status.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Alt_Status.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Position_x.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Position_x.data = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Position_y.data = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Position_y.data = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
