// Generated by gencpp from file ross/confg_modeResponse.msg
// DO NOT EDIT!


#ifndef ROSS_MESSAGE_CONFG_MODERESPONSE_H
#define ROSS_MESSAGE_CONFG_MODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ross
{
template <class ContainerAllocator>
struct confg_modeResponse_
{
  typedef confg_modeResponse_<ContainerAllocator> Type;

  confg_modeResponse_()
    : feedback(false)  {
    }
  confg_modeResponse_(const ContainerAllocator& _alloc)
    : feedback(false)  {
  (void)_alloc;
    }



   typedef uint8_t _feedback_type;
  _feedback_type feedback;





  typedef boost::shared_ptr< ::ross::confg_modeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ross::confg_modeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct confg_modeResponse_

typedef ::ross::confg_modeResponse_<std::allocator<void> > confg_modeResponse;

typedef boost::shared_ptr< ::ross::confg_modeResponse > confg_modeResponsePtr;
typedef boost::shared_ptr< ::ross::confg_modeResponse const> confg_modeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ross::confg_modeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ross::confg_modeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ross::confg_modeResponse_<ContainerAllocator1> & lhs, const ::ross::confg_modeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.feedback == rhs.feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ross::confg_modeResponse_<ContainerAllocator1> & lhs, const ::ross::confg_modeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ross

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ross::confg_modeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ross::confg_modeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ross::confg_modeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ross::confg_modeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ross::confg_modeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ross::confg_modeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ross::confg_modeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1f168a39479bedb24dba7a087426182";
  }

  static const char* value(const ::ross::confg_modeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1f168a39479bedbULL;
  static const uint64_t static_value2 = 0x24dba7a087426182ULL;
};

template<class ContainerAllocator>
struct DataType< ::ross::confg_modeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ross/confg_modeResponse";
  }

  static const char* value(const ::ross::confg_modeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ross::confg_modeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool feedback\n"
"\n"
;
  }

  static const char* value(const ::ross::confg_modeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ross::confg_modeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct confg_modeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ross::confg_modeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ross::confg_modeResponse_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSS_MESSAGE_CONFG_MODERESPONSE_H
