// Generated by gencpp from file ross/land.msg
// DO NOT EDIT!


#ifndef ROSS_MESSAGE_LAND_H
#define ROSS_MESSAGE_LAND_H

#include <ros/service_traits.h>


#include <ross/landRequest.h>
#include <ross/landResponse.h>


namespace ross
{

struct land
{

typedef landRequest Request;
typedef landResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct land
} // namespace ross


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ross::land > {
  static const char* value()
  {
    return "8418e6fd9e3883e9757a349fc01ca1f9";
  }

  static const char* value(const ::ross::land&) { return value(); }
};

template<>
struct DataType< ::ross::land > {
  static const char* value()
  {
    return "ross/land";
  }

  static const char* value(const ::ross::land&) { return value(); }
};


// service_traits::MD5Sum< ::ross::landRequest> should match
// service_traits::MD5Sum< ::ross::land >
template<>
struct MD5Sum< ::ross::landRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ross::land >::value();
  }
  static const char* value(const ::ross::landRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ross::landRequest> should match
// service_traits::DataType< ::ross::land >
template<>
struct DataType< ::ross::landRequest>
{
  static const char* value()
  {
    return DataType< ::ross::land >::value();
  }
  static const char* value(const ::ross::landRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ross::landResponse> should match
// service_traits::MD5Sum< ::ross::land >
template<>
struct MD5Sum< ::ross::landResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ross::land >::value();
  }
  static const char* value(const ::ross::landResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ross::landResponse> should match
// service_traits::DataType< ::ross::land >
template<>
struct DataType< ::ross::landResponse>
{
  static const char* value()
  {
    return DataType< ::ross::land >::value();
  }
  static const char* value(const ::ross::landResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSS_MESSAGE_LAND_H
