// Generated by gencpp from file ross/RTL.msg
// DO NOT EDIT!


#ifndef ROSS_MESSAGE_RTL_H
#define ROSS_MESSAGE_RTL_H

#include <ros/service_traits.h>


#include <ross/RTLRequest.h>
#include <ross/RTLResponse.h>


namespace ross
{

struct RTL
{

typedef RTLRequest Request;
typedef RTLResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RTL
} // namespace ross


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ross::RTL > {
  static const char* value()
  {
    return "6c7b48717ccfef833a363078363def6f";
  }

  static const char* value(const ::ross::RTL&) { return value(); }
};

template<>
struct DataType< ::ross::RTL > {
  static const char* value()
  {
    return "ross/RTL";
  }

  static const char* value(const ::ross::RTL&) { return value(); }
};


// service_traits::MD5Sum< ::ross::RTLRequest> should match
// service_traits::MD5Sum< ::ross::RTL >
template<>
struct MD5Sum< ::ross::RTLRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ross::RTL >::value();
  }
  static const char* value(const ::ross::RTLRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ross::RTLRequest> should match
// service_traits::DataType< ::ross::RTL >
template<>
struct DataType< ::ross::RTLRequest>
{
  static const char* value()
  {
    return DataType< ::ross::RTL >::value();
  }
  static const char* value(const ::ross::RTLRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ross::RTLResponse> should match
// service_traits::MD5Sum< ::ross::RTL >
template<>
struct MD5Sum< ::ross::RTLResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ross::RTL >::value();
  }
  static const char* value(const ::ross::RTLResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ross::RTLResponse> should match
// service_traits::DataType< ::ross::RTL >
template<>
struct DataType< ::ross::RTLResponse>
{
  static const char* value()
  {
    return DataType< ::ross::RTL >::value();
  }
  static const char* value(const ::ross::RTLResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSS_MESSAGE_RTL_H
