// Generated by gencpp from file ross/RTLResponse.msg
// DO NOT EDIT!


#ifndef ROSS_MESSAGE_RTLRESPONSE_H
#define ROSS_MESSAGE_RTLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ross
{
template <class ContainerAllocator>
struct RTLResponse_
{
  typedef RTLResponse_<ContainerAllocator> Type;

  RTLResponse_()
    : confirm_mode(false)  {
    }
  RTLResponse_(const ContainerAllocator& _alloc)
    : confirm_mode(false)  {
  (void)_alloc;
    }



   typedef uint8_t _confirm_mode_type;
  _confirm_mode_type confirm_mode;





  typedef boost::shared_ptr< ::ross::RTLResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ross::RTLResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RTLResponse_

typedef ::ross::RTLResponse_<std::allocator<void> > RTLResponse;

typedef boost::shared_ptr< ::ross::RTLResponse > RTLResponsePtr;
typedef boost::shared_ptr< ::ross::RTLResponse const> RTLResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ross::RTLResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ross::RTLResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ross::RTLResponse_<ContainerAllocator1> & lhs, const ::ross::RTLResponse_<ContainerAllocator2> & rhs)
{
  return lhs.confirm_mode == rhs.confirm_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ross::RTLResponse_<ContainerAllocator1> & lhs, const ::ross::RTLResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ross

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ross::RTLResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ross::RTLResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ross::RTLResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ross::RTLResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ross::RTLResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ross::RTLResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ross::RTLResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c7b48717ccfef833a363078363def6f";
  }

  static const char* value(const ::ross::RTLResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c7b48717ccfef83ULL;
  static const uint64_t static_value2 = 0x3a363078363def6fULL;
};

template<class ContainerAllocator>
struct DataType< ::ross::RTLResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ross/RTLResponse";
  }

  static const char* value(const ::ross::RTLResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ross::RTLResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool confirm_mode\n"
"\n"
;
  }

  static const char* value(const ::ross::RTLResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ross::RTLResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.confirm_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RTLResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ross::RTLResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ross::RTLResponse_<ContainerAllocator>& v)
  {
    s << indent << "confirm_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.confirm_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSS_MESSAGE_RTLRESPONSE_H
