// Generated by gencpp from file ross/takeoffResponse.msg
// DO NOT EDIT!


#ifndef ROSS_MESSAGE_TAKEOFFRESPONSE_H
#define ROSS_MESSAGE_TAKEOFFRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ross
{
template <class ContainerAllocator>
struct takeoffResponse_
{
  typedef takeoffResponse_<ContainerAllocator> Type;

  takeoffResponse_()
    : ok(0.0)  {
    }
  takeoffResponse_(const ContainerAllocator& _alloc)
    : ok(0.0)  {
  (void)_alloc;
    }



   typedef float _ok_type;
  _ok_type ok;





  typedef boost::shared_ptr< ::ross::takeoffResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ross::takeoffResponse_<ContainerAllocator> const> ConstPtr;

}; // struct takeoffResponse_

typedef ::ross::takeoffResponse_<std::allocator<void> > takeoffResponse;

typedef boost::shared_ptr< ::ross::takeoffResponse > takeoffResponsePtr;
typedef boost::shared_ptr< ::ross::takeoffResponse const> takeoffResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ross::takeoffResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ross::takeoffResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ross::takeoffResponse_<ContainerAllocator1> & lhs, const ::ross::takeoffResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ok == rhs.ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ross::takeoffResponse_<ContainerAllocator1> & lhs, const ::ross::takeoffResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ross

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ross::takeoffResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ross::takeoffResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ross::takeoffResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ross::takeoffResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ross::takeoffResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ross::takeoffResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ross::takeoffResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2991260901f1e54fdc610afd7d79eeb1";
  }

  static const char* value(const ::ross::takeoffResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2991260901f1e54fULL;
  static const uint64_t static_value2 = 0xdc610afd7d79eeb1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ross::takeoffResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ross/takeoffResponse";
  }

  static const char* value(const ::ross::takeoffResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ross::takeoffResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 ok\n"
"\n"
;
  }

  static const char* value(const ::ross::takeoffResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ross::takeoffResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct takeoffResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ross::takeoffResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ross::takeoffResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<float>::stream(s, indent + "  ", v.ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSS_MESSAGE_TAKEOFFRESPONSE_H
