// Generated by gencpp from file ross/takeoffRequest.msg
// DO NOT EDIT!


#ifndef ROSS_MESSAGE_TAKEOFFREQUEST_H
#define ROSS_MESSAGE_TAKEOFFREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ross
{
template <class ContainerAllocator>
struct takeoffRequest_
{
  typedef takeoffRequest_<ContainerAllocator> Type;

  takeoffRequest_()
    : Height(0.0)  {
    }
  takeoffRequest_(const ContainerAllocator& _alloc)
    : Height(0.0)  {
  (void)_alloc;
    }



   typedef float _Height_type;
  _Height_type Height;





  typedef boost::shared_ptr< ::ross::takeoffRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ross::takeoffRequest_<ContainerAllocator> const> ConstPtr;

}; // struct takeoffRequest_

typedef ::ross::takeoffRequest_<std::allocator<void> > takeoffRequest;

typedef boost::shared_ptr< ::ross::takeoffRequest > takeoffRequestPtr;
typedef boost::shared_ptr< ::ross::takeoffRequest const> takeoffRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ross::takeoffRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ross::takeoffRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ross::takeoffRequest_<ContainerAllocator1> & lhs, const ::ross::takeoffRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Height == rhs.Height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ross::takeoffRequest_<ContainerAllocator1> & lhs, const ::ross::takeoffRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ross

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ross::takeoffRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ross::takeoffRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ross::takeoffRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ross::takeoffRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ross::takeoffRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ross::takeoffRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ross::takeoffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7ccd79f4555d5c764e8e40707445fd8a";
  }

  static const char* value(const ::ross::takeoffRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7ccd79f4555d5c76ULL;
  static const uint64_t static_value2 = 0x4e8e40707445fd8aULL;
};

template<class ContainerAllocator>
struct DataType< ::ross::takeoffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ross/takeoffRequest";
  }

  static const char* value(const ::ross::takeoffRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ross::takeoffRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 Height\n"
;
  }

  static const char* value(const ::ross::takeoffRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ross::takeoffRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct takeoffRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ross::takeoffRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ross::takeoffRequest_<ContainerAllocator>& v)
  {
    s << indent << "Height: ";
    Printer<float>::stream(s, indent + "  ", v.Height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSS_MESSAGE_TAKEOFFREQUEST_H
